DROP TABLE TESTVEHICLE IF EXISTS;

CREATE TABLE "TESTVEHICLE"
( ID INT NOT NULL,
"VEHICLENUMBER" VARCHAR(10),
"BRAND" VARCHAR(100),
"COUNTRY" VARCHAR(100),
"MODELNAME" VARCHAR(35),
"MODELYEAR" VARCHAR(35),
PRIMARY KEY (ID)
) ;