DROP TABLE TESTVEHICLE IF EXISTS;
DROP sequence vehicle_seq if EXISTS;

CREATE TABLE "TESTVEHICLE"
( ID INT NOT NULL,
"VEHICLENUMBER" VARCHAR(10),
"BRAND" VARCHAR(100),
"COUNTRY" VARCHAR(100),
"MODELNAME" VARCHAR(35),
"MODELYEAR" VARCHAR(35),
PRIMARY KEY (ID)
) ;

create sequence vehicle_seq increment by 1;

INSERT INTO TESTVEHICLE(ID,vehiclenumber,brand,country,modelname,modelyear)  VALUES(1,'MH12 34','BM','IN','Benz','2000')
